In [ ]:
import pandas as pd
import numpy as np

m2_plus = pd.read_excel('M2+/m2_plus.xlsx')
yikou = pd.read_excel('M2+/风控跟踪表.xlsx')
m2_plus = m2_plus[['贷款编号','贷款金额','产品名称','SA工号','SA姓名']]
m2_plus['贷款编号'] = m2_plus['贷款编号'].astype('O')
m2_plus['SA工号'] = m2_plus['SA工号'].astype('O')

m2 = pd.read_excel('首次M2/首次M2明细表.xlsx')
m2 = m2[['贷款编号','贷款金额','产品名称','SA工号','SA姓名']]
m2['贷款编号'] = m2['贷款编号'].astype('O')
m2['SA工号'] = m2['SA工号'].astype('O')
m2_over=pd.pivot_table(m2,index=['SA工号'],values=['贷款编号'],aggfunc=[len])
m2_over_rate = pd.read_excel("首次m2/m2_over_rate.xlsx")
m2_over = pd.merge(m2_over_rate,m2_over,on="SA工号",how="left",suffixes=('','_y'))
m2_over['首次M2逾期率'] = 0.0
m2_over

d:\ProgramData\Miniconda3\envs\lihuaqi\lib\site-packages\pandas\core\reshape\merge.py:543: UserWarning: merging between different levels can give an unintended result (1 levels on the left, 2 on the right)
  warnings.warn(msg, UserWarning)

          SA工号          SA姓名  首次M2注册数  (len, 贷款编号)  首次M2逾期率
0     23240258    信用借款业务虚拟代表     4335          NaN      0.0
1      4160024           邓培杰       45          NaN      0.0
2     19130028      斯米巴提·努尔兰       21          1.0      0.0
3     24250239  信用借款业务虚拟代表xx      303          NaN      0.0
4     25010009           岳奥鹏        3          NaN      0.0
5      3120156           陈利纳       17          NaN      0.0
6      8100165           画金星       18          NaN      0.0
7     24050004     西尔力·买买提依明       35          2.0      0.0
8     26250412           张亚龙       62          2.0      0.0
9      4230049       达伍提·阿力木       58          1.0      0.0
10    26100323           张锦鹏       51          6.0      0.0
11    24050005      西尔艾力·依米提       19          3.0      0.0
12     1020009  阿布都合里力·阿不里米提       16          NaN      0.0
13    12120215            李莉       68          1.0      0.0
14    12190178            罗爽       91          3.0      0.0
15    26040090           赵东煜       19          3.0      0.0
16    24250247  信用借款业务虚拟代表gy       12          NaN      0.0
17    12100316           卢建红       32          1.0      0.0
18    26110030           张可心       32          1.0      0.0
19    12200121           兰涛江       37          2.0      0.0
20    23190140            王森       53          2.0      0.0
21    12250654           罗永廷       52          1.0      0.0
22    24070027           徐国娇       13          NaN      0.0
23    23100225           汪建丽       25          NaN      0.0
24    12190020           李世杰       63          1.0      0.0
25    12260113           刘阵疆       13          NaN      0.0
26    13230017           马文海       18          NaN      0.0
27    23070065           王国伟        4          1.0      0.0
28     7120078      古力扎尔·买买提       22          NaN      0.0
29    23260175           王中宇       35          1.0      0.0
...        ...           ...      ...          ...      ...
3245   2130012           白慕荣        5          NaN      0.0
3246  14100017           倪家乐        7          2.0      0.0
3247  26240175           张晓磊        0          NaN      0.0
3248   7080054           顾洪斌        2          NaN      0.0
3249   7120089      古丽皮耶·吐尔逊        1          NaN      0.0
3250   7130028            高梅        3          NaN      0.0
3251  23170138           吴琴琴        8          NaN      0.0
3252   3200045            常天        1          NaN      0.0
3253  12260297           李志平        0          NaN      0.0
3254  12240520            李雪        0          NaN      0.0
3255   4100099            单晶        3          NaN      0.0
3256  25030094           袁翠波        0          NaN      0.0
3257   2130011     布玛力亚木·艾则孜        4          1.0      0.0
3258  24250251           钱亚凤        2          NaN      0.0
3259   1120023      艾力·麦提尼亚孜        2          NaN      0.0
3260   1050008     艾尔库特·艾合拜尔        3          NaN      0.0
3261   1120014    阿力木江·阿合尼亚孜        3          NaN      0.0
3262  23120213           王利宁        2          NaN      0.0
3263  16050004       帕尔哈提·努尔        4          NaN      0.0
3264  20050001           NaN        0          NaN      0.0
3265  25100218           杨继璇        2          NaN      0.0
3266   1040011       阿迪力·吾甫尔        1          NaN      0.0
3267   1110008            安康        2          NaN      0.0
3268  12240498      李香禹·民生通讯        2          NaN      0.0
3269  23120211            王乐        2          NaN      0.0
3270  25070040           雅各布        0          NaN      0.0
3271  12020073            李斌        0          NaN      0.0
3272  13180020            马瑞        1          NaN      0.0
3273  26250547            张印        0          NaN      0.0
3274  10130027           姜梦菊        0          NaN      0.0

[3275 rows x 5 columns]

In [18]:
#首次M2逾期率计算
for i in range(len(m2_over)):
    m2_over.loc[i,'首次M2逾期率'] = (m2_over.iloc[i,3] /m2_over.iloc[i,2])*100
m2_over['SA工号'] = m2_over['SA工号'].astype('O')
m2_over = m2_over[['SA工号','首次M2逾期率']]

In [19]:
m2_over

          SA工号    首次M2逾期率
0     23240258        NaN
1      4160024        NaN
2     19130028   4.761905
3     24250239        NaN
4     25010009        NaN
5      3120156        NaN
6      8100165        NaN
7     24050004   5.714286
8     26250412   3.225806
9      4230049   1.724138
10    26100323  11.764706
11    24050005  15.789474
12     1020009        NaN
13    12120215   1.470588
14    12190178   3.296703
15    26040090  15.789474
16    24250247        NaN
17    12100316   3.125000
18    26110030   3.125000
19    12200121   5.405405
20    23190140   3.773585
21    12250654   1.923077
22    24070027        NaN
23    23100225        NaN
24    12190020   1.587302
25    12260113        NaN
26    13230017        NaN
27    23070065  25.000000
28     7120078        NaN
29    23260175   2.857143
...        ...        ...
3245   2130012        NaN
3246  14100017  28.571429
3247  26240175        NaN
3248   7080054        NaN
3249   7120089        NaN
3250   7130028        NaN
3251  23170138        NaN
3252   3200045        NaN
3253  12260297        NaN
3254  12240520        NaN
3255   4100099        NaN
3256  25030094        NaN
3257   2130011  25.000000
3258  24250251        NaN
3259   1120023        NaN
3260   1050008        NaN
3261   1120014        NaN
3262  23120213        NaN
3263  16050004        NaN
3264  20050001        NaN
3265  25100218        NaN
3266   1040011        NaN
3267   1110008        NaN
3268  12240498        NaN
3269  23120211        NaN
3270  25070040        NaN
3271  12020073        NaN
3272  13180020        NaN
3273  26250547        NaN
3274  10130027        NaN

[3275 rows x 2 columns]

In [20]:
yikou = yikou[['贷款编号','扣押月份','退还月份']]
yikou['贷款编号'] = yikou['贷款编号'].astype('O')
m2_plus = pd.merge(m2_plus,yikou,on="贷款编号",how="left")

In [21]:
m2_plus_ = m2_plus.copy()
for i in range(len(m2_plus_)):
    if np.isnan(m2_plus_.loc[i,"扣押月份"]) == True or np.isnan(m2_plus_.loc[i,"退还月份"])==True:
        m2_plus_.drop([i],inplace=True)


for i in range(len(m2_plus)):
    if np.isnan(m2_plus.loc[i, "扣押月份"]) == False:
        m2_plus.drop([i], inplace=True)
    else:
        pass

m2_plus = m2_plus.reset_index(drop=True)  # 对索引重置
m2_plus = pd.concat([m2_plus,m2_plus_],ignore_index=True)
m2_plus = m2_plus[['贷款编号','贷款金额','产品名称','SA工号','SA姓名']]
zmd = pd.read_excel('首次M2/主门店汇总.xlsx')
zmd['贷款编号'] = zmd['贷款编号'].astype('O')
m2_plus = pd.merge(m2_plus, zmd, on="贷款编号", how="left")
m2_plus

                     贷款编号  贷款金额         产品名称      SA工号          SA姓名  每日提成金额
0      652102017111202955  1999         优惠产品  25100191           叶金霞     NaN
1      652102017111203588  2300         10期贷   1050003      艾尔肯·艾尼瓦尔     NaN
2      532902017111206083  2698         优惠产品  25170088           杨秋云     NaN
3      530102017111200542  1899         优惠产品  23250423           魏勇强     NaN
4      522202017111206424  2999         优惠产品  26120302           朱林林     NaN
5      650102017111204624  3000         一般产品  25060054           杨丰华     NaN
6      650102017111204817  1598         一般产品  12100477           刘嘉宇     NaN
7      620102017111202584   800         优惠产品  23140018           王娜娜   300.0
8      650102017111504628  2999         一般产品  25200068           殷廷龙     NaN
9      530102017111505109  2698         优惠产品  24240093           肖宪涛     NaN
10     610102017111505045  2999         优惠产品  12130195            雷鸣     NaN
11     610102017111505069  2399         优惠产品  12250541           刘雨晨   400.0
12     520102017111505740  2999         一般产品   7260033           古正伟     NaN
13     141002017111505595  2500       山西10期贷  24110019           邢康兵     NaN
14     640102017111504029  2798         10期贷   8140013           韩宁华     NaN
15     513402017111503976  1798         优惠产品  12060110            李凡     NaN
16     654202017111504477  2500         一般产品   1120017   阿勒玛古丽·吐尔德别克     NaN
17     654202017111504664  2900         一般产品  12120165           李玲艺     NaN
18     653102017111204534  2500         10期贷   2190020       布苏丽坦·努尔     NaN
19     520202017111605981  2998         优惠产品  26240080           张兴江     NaN
20     522402017111607156  2499         10期贷  12240128            刘鑫     NaN
21     522602017111601279  1098         优惠产品  23170127            吴倩     NaN
22     650102017111606970  2998         一般产品  12070101           鲁国威     NaN
23     659002017111205649  3000         优惠产品   3200038           陈天顺     NaN
24     652902017111206169  1400         10期贷  13080044      莫合特尔·买买提     NaN
25     652902017111206172  2699         一般产品  26120265           翟丽敏     NaN
26     652902017111204537  2698         一般产品   3080096           陈红超     NaN
27     630102017111204713  2998         优惠产品   8260096           韩志清     NaN
28     650102017111505168  3000         一般产品   8120099           贺拉拉     NaN
29     653102017111502442  2699         一般产品   1140001     阿尼克孜·麦麦提明     NaN
...                   ...   ...          ...       ...           ...     ...
12249  640502018020804188  3000         一般产品  23170110           吴全洲     NaN
12250  653102018021407266  2799         一般产品  12170175           罗庆梅     NaN
12251  141002018020802923  2500         优惠产品  24250134           郇永潇     NaN
12252  652102018020803399  1518         10期贷  19120091     赛丽米古丽·买买提     NaN
12253  652102018020807272  4500         一般产品  17080016           屈会宾     NaN
12254  652202018020908049  3000         优惠产品  25120117            袁磊     NaN
12255  653102018022004026  2600         一般产品   7120082      古丽努尔·马木提     NaN
12256  513402018021402431  2888         优惠产品  25020042            杨波     NaN
12257  652802018020906681  3300         一般产品  18260022      热孜古丽·艾尼玩     NaN
12258  522702018020804790  1399         优惠产品  26040077           郑德会     NaN
12259  540002018022003153  3000         一般产品  26240336            扎西     NaN
12260  654002018021407001  1501         一般产品   4130030            邓明     NaN
12261  150802018021403535  3000         一般产品  25040044            杨栋     NaN
12262  150802018021406168  2998         一般产品   3250145            曹宇     NaN
12263  520102018022002381  2499         优惠产品   4100078            杜焦   400.0
12264  522202018020804526  1935  贵州运营商专享12期B  13240125            梅旭     NaN
12265  653002018020907788  2900         10期贷  10080046    佳罕娜依·图尔迪胡力     NaN
12266  653002018020908464  2800         一般产品  20080045      托合提努尔·托昆     NaN
12267  653002018020805738  1000         一般产品  13140016      木尼热·苏拉依曼     NaN
12268  654002018020803179  3299         一般产品  12040125           刘冬亮     NaN
12269  520102018020805243  3588         优惠产品   1260010           敖正辉     NaN
12270  654002018020906908  1100         一般产品   1040008       阿迪兰·达吾尔     NaN
12271  654002018020907038  2999         一般产品  12200121           兰涛江     NaN
12272  653102018020906023  1499         一般产品   7120073     古丽乃再尔·亚库普     NaN
12273  652102018022002389  2599         优惠产品  26250381           遭永成   400.0
12274  652102018022002820  1300         一般产品  19020016       沙比提·买买提     NaN
12275  653102017111606929  1509         一般产品  26100346           张建华     NaN
12276  150802017112404300  2199         一般产品  12140043            李楠     NaN
12277  540102017112204991  2699         一般产品  26230138           朱文鼎     NaN
12278  654002017112101290  1509         一般产品  11120018  卡力比亚提·比克木哈麦提     NaN

[12279 rows x 6 columns]

In [ ]:
m2_plus

In [22]:
m2_plus["扣罚"] = 0
for i in range(len(m2_plus)):
    if m2_plus.loc[i, '产品名称'] == '一般产品' or m2_plus.loc[i, '产品名称'] == '优惠产品' or m2_plus.loc[i, '产品名称'] == '广州服务类产品':
        if m2_plus.loc[i, '贷款金额'] >= 1500:
            m2_plus.loc[i, '扣罚'] = 100
        else:
            m2_plus.loc[i, '扣罚'] = 50
    elif m2_plus.loc[i, '产品名称'] == '003产品':
        m2_plus.loc[i, '扣罚'] = 30
    elif m2_plus.loc[i,'产品名称'] =="U客购":
        m2_plus.loc[i,"扣罚"] = 180
    else:
        if m2_plus.loc[i, '贷款金额'] >= 2300:
            m2_plus.loc[i, '扣罚'] = 66
        elif 1800 <= m2_plus.loc[i, '贷款金额'] < 2300:
            m2_plus.loc[i, '扣罚'] = 44
        else:
            m2_plus.loc[i, '扣罚'] = 22

m2_plus["最终扣罚"] = 0
for i in range(len(m2_plus)):
    if np.isnan(m2_plus.loc[i, '每日提成金额']):
        m2_plus.loc[i, '最终扣罚'] = m2_plus.loc[i, '扣罚']
    else:
        m2_plus.loc[i, '最终扣罚'] = m2_plus.loc[i, '每日提成金额']

m2_plus['逾期等级'] = 'M2+'

In [23]:
m2_plus

,贷款编号,贷款金额,产品名称,SA工号,SA姓名,每日提成金额,扣罚,最终扣罚,逾期等级
0,652102017111202955,1999,优惠产品,25100191,叶金霞,NaN,100,100.0,M2+
1,652102017111203588,2300,10期贷,1050003,艾尔肯·艾尼瓦尔,NaN,66,66.0,M2+
2,532902017111206083,2698,优惠产品,25170088,杨秋云,NaN,100,100.0,M2+
3,530102017111200542,1899,优惠产品,23250423,魏勇强,NaN,100,100.0,M2+
4,522202017111206424,2999,优惠产品,26120302,朱林林,NaN,100,100.0,M2+
5,650102017111204624,3000,一般产品,25060054,杨丰华,NaN,100,100.0,M2+
6,650102017111204817,1598,一般产品,12100477,刘嘉宇,NaN,100,100.0,M2+
7,620102017111202584,800,优惠产品,23140018,王娜娜,300.0,50,300.0,M2+
8,650102017111504628,2999,一般产品,25200068,殷廷龙,NaN,100,100.0,M2+
9,530102017111505109,2698,优惠产品,24240093,肖宪涛,NaN,100,100.0,M2+
10,610102017111505045,2999,优惠产品,12130195,雷鸣,NaN,100,100.0,M2+
11,610102017111505069,2399,优惠产品,12250541,刘雨晨,400.0,100,400.0,M2+
12,520102017111505740,2999,一般产品,7260033,古正伟,NaN,100,100.0,M2+
13,141002017111505595,2500,山西10期贷,24110019,邢康兵,NaN,66,66.0,M2+
14,640102017111504029,2798,10期贷,8140013,韩宁华,NaN,66,66.0,M2+
15,513402017111503976,1798,优惠产品,12060110,李凡,NaN,100,100.0,M2+
16,654202017111504477,2500,一般产品,1120017,阿勒玛古丽·吐尔德别克,NaN,100,100.0,M2+
17,654202017111504664,2900,一般产品,12120165,李玲艺,NaN,100,100.0,M2+
18,653102017111204534,2500,10期贷,2190020,布苏丽坦·努尔,NaN,66,66.0,M2+
19,520202017111605981,2998,优惠产品,26240080,张兴江,NaN,100,100.0,M2+
20,522402017111607156,2499,10期贷,12240128,刘鑫,NaN,66,66.0,M2+
21,522602017111601279,1098,优惠产品,23170127,吴倩,NaN,50,50.0,M2+
22,650102017111606970,2998,一般产品,12070101,鲁国威,NaN,100,100.0,M2+
23,659002017111205649,3000,优惠产品,3200038,陈天顺,NaN,100,100.0,M2+
24,652902017111206169,1400,10期贷,13080044,莫合特尔·买买提,NaN,22,22.0,M2+
25,652902017111206172,2699,一般产品,26120265,翟丽敏,NaN,100,100.0,M2+
26,652902017111204537,2698,一般产品,3080096,陈红超,NaN,100,100.0,M2+
27,630102017111204713,2998,优惠产品,8260096,韩志清,NaN,100,100.0,M2+
28,650102017111505168,3000,一般产品,8120099,贺拉拉,NaN,100,100.0,M2+
29,653102017111502442,2699,一般产品,1140001,阿尼克孜·麦麦提明,NaN,100,100.0,M2+
...,...,...,...,...,...,...,...,...,...
12249,640502018020804188,3000,一般产品,23170110,吴全洲,NaN,100,100.0,M2+
12250,653102018021407266,2799,一般产品,12170175,罗庆梅,NaN,100,100.0,M2+
12251,141002018020802923,2500,优惠产品,24250134,郇永潇,NaN,100,100.0,M2+
12252,652102018020803399,1518,10期贷,19120091,赛丽米古丽·买买提,NaN,22,22.0,M2+
12253,652102018020807272,4500,一般产品,17080016,屈会宾,NaN,100,100.0,M2+
12254,652202018020908049,3000,优惠产品,25120117,袁磊,NaN,100,100.0,M2+
12255,653102018022004026,2600,一般产品,7120082,古丽努尔·马木提,NaN,100,100.0,M2+
12256,513402018021402431,2888,优惠产品,25020042,杨波,NaN,100,100.0,M2+
12257,652802018020906681,3300,一般产品,18260022,热孜古丽·艾尼玩,NaN,100,100.0,M2+
12258,522702018020804790,1399,优惠产品,26040077,郑德会,NaN,50,50.0,M2+
12259,540002018022003153,3000,一般产品,26240336,扎西,NaN,100,100.0,M2+
12260,654002018021407001,1501,一般产品,4130030,邓明,NaN,100,100.0,M2+
12261,150802018021403535,3000,一般产品,25040044,杨栋,NaN,100,100.0,M2+
12262,150802018021406168,2998,一般产品,3250145,曹宇,NaN,100,100.0,M2+
12263,520102018022002381,2499,优惠产品,4100078,杜焦,400.0,100,400.0,M2+
12264,522202018020804526,1935,贵州运营商专享12期B,13240125,梅旭,NaN,44,44.0,M2+
12265,653002018020907788,2900,10期贷,10080046,佳罕娜依·图尔迪胡力,NaN,66,66.0,M2+
12266,653002018020908464,2800,一般产品,20080045,托合提努尔·托昆,NaN,100,100.0,M2+
12267,653002018020805738,1000,一般产品,13140016,木尼热·苏拉依曼,NaN,50,50.0,M2+
12268,654002018020803179,3299,一般产品,12040125,刘冬亮,NaN,100,100.0,M2+
12269,520102018020805243,3588,优惠产品,1260010,敖正辉,NaN,100,100.0,M2+
12270,654002018020906908,1100,一般产品,1040008,阿迪兰·达吾尔,NaN,50,50.0,M2+
12271,654002018020907038,2999,一般产品,12200121,兰涛江,NaN,100,100.0,M2+
12272,653102018020906023,1499,一般产品,7120073,古丽乃再尔·亚库普,NaN,50,50.0,M2+
12273,652102018022002389,2599,优惠产品,26250381,遭永成,400.0,100,400.0,M2+
12274,652102018022002820,1300,一般产品,19020016,沙比提·买买提,NaN,50,50.0,M2+
12275,653102017111606929,1509,一般产品,26100346,张建华,NaN,100,100.0,M2+
12276,150802017112404300,2199,一般产品,12140043,李楠,NaN,100,100.0,M2+
12277,540102017112204991,2699,一般产品,26230138,朱文鼎,NaN,100,100.0,M2+
12278,654002017112101290,1509,一般产品,11120018,卡力比亚提·比克木哈麦提,NaN,100,100.0,M2+

In [24]:
m2_SA = m2_plus.drop_duplicates(["SA工号"])
m2_SA = m2_SA[['SA工号']]
overdue_rate_m3 = pd.read_excel("首次M2/Overdue_rate_M3.xlsx")
overdue_rate_m3['SA工号'] = overdue_rate_m3['SA工号'].astype('O')
m2_SA = pd.merge(m2_SA,m2_over,on="SA工号",how="left",suffixes=('','_y'))
m2_SA = pd.merge(m2_SA,overdue_rate_m3,on="SA工号",how="left",suffixes=('','_y'))

In [25]:
people_list = pd.read_excel("人员清单/people_listing.xlsx")
people_list['SA工号'] = people_list['SA工号'].astype('O')
m2_SA = pd.merge(m2_SA,people_list, on="SA工号",how="left",suffixes=('','_y'))
m2_SA

          SA工号    首次M2逾期率         SA姓名  M3+逾期率(%)  在职天数
0     25100191        NaN          叶金霞       1.41   277
1      1050003        NaN     艾尔肯·艾尼瓦尔       0.90   212
2     25170088        NaN          杨秋云      20.29   431
3     23250423        NaN          魏勇强       7.50   289
4     26120302   4.761905          朱林林      11.76   304
5     25060054  11.538462          杨丰华       3.17   548
6     12100477        NaN          刘嘉宇       6.35   307
7     23140018        NaN          王娜娜       5.45   938
8     25200068   4.081633          殷廷龙       2.31   219
9     24240093   3.125000          肖宪涛      10.47   361
10    12130195   4.878049           雷鸣       7.58   200
11    12250541   4.000000          刘雨晨       3.90   512
12     7260033   4.838710          古正伟       1.97   667
13    24110019        NaN          邢康兵       0.00   290
14     8140013        NaN          韩宁华       2.22   560
15    12060110        NaN           李凡       1.27   261
16     1120017  22.222222  阿勒玛古丽·吐尔德别克      22.22   266
17    12120165   8.333333          李玲艺       0.00   669
18     2190020  25.000000      布苏丽坦·努尔       6.94   283
19    26240080  14.285714          张兴江      11.27   778
20    12240128        NaN           刘鑫      13.04   787
21    23170127        NaN           吴倩       3.85   221
22    12070101        NaN          鲁国威       2.70   226
23     3200038        NaN          陈天顺       0.00   305
24    13080044  13.333333     莫合特尔·买买提       7.32   308
25    26120265  10.000000          翟丽敏       8.51   454
26     3080096  13.513514          陈红超       3.82   315
27     8260096   7.142857          韩志清      15.19   219
28     8120099   6.896552          贺拉拉       4.55   393
29     1140001   6.382979    阿尼克孜·麦麦提明       2.84   318
...        ...        ...          ...        ...   ...
3001   8120126        NaN          黄良腾       9.09   158
3002  12060084        NaN           雷帆       5.26   511
3003  26260170        NaN          张子贵       0.00   186
3004   3120160   8.333333          陈丽娜       0.00   112
3005  12240507   1.438849          刘显林       1.37   108
3006  12100531        NaN          蓝健勇       0.00   169
3007  12240443  25.000000          刘学海      14.81   281
3008  23230050   3.030303          王伟龙       2.75   725
3009  25260114   5.882353           杨志       0.00   135
3010  23170121        NaN           王倩       3.90   262
3011  12180034        NaN          刘仁俊       8.64   734
3012  19190033   4.761905           孙帅       6.25   291
3013  25240200  20.000000           冶晓      23.91   141
3014  16120026  10.526316          彭良盛       0.00   584
3015  12100175        NaN           李吉       4.05   754
3016  26250296        NaN          张玉爽       0.00   644
3017  12250733   5.882353          林玉亮      12.50   135
3018   3100196   6.250000          成敬琴      10.00   113
3019   4100097  12.500000          董杰堂       7.69   161
3020  12230220        NaN          李文龙       7.14   144
3021  12250723        NaN           刘勇       6.25   168
3022   8040029        NaN          韩得库       0.00   695
3023  12080333   6.060606          龙海波       6.25   185
3024  12060100        NaN          李飞龙      11.54   325
3025  26080258   2.500000          张海锋       7.04   196
3026  23230119        NaN          吴伟强      15.38   246
3027  10070008   4.255319           金刚       4.04   493
3028   7060028   3.846154           高飞       3.65   125
3029  13140016   5.263158     木尼热·苏拉依曼       4.08   144
3030  12200121   5.405405          兰涛江       4.92   277

[3031 rows x 5 columns]

In [26]:

for i in range(len(m2_SA)):
    if np.isnan(m2_SA.loc[i,"首次M2逾期率"]):
        m2_SA.loc[i,"首次M2逾期率"] = 0
    else:
        pass

for i in range(len(m2_SA)):
    if np.isnan(m2_SA.loc[i,"M3+逾期率(%)"]):
        m2_SA.loc[i,"M3+逾期率(%)"] = 0
    else:
        pass

m2_SA["是否免除扣罚"] = 0
for i in range(len(m2_SA)):
    if m2_SA.loc[i,"在职天数"] >= 90 :
        if m2_SA.loc[i,"首次M2逾期率"] < 5.0:
            if m2_SA.loc[i,"M3+逾期率(%)"] < 7.0:
                m2_SA.loc[i,"是否免除扣罚"] = 1
            else:
                m2_SA.loc[i,"是否免除扣罚"] = 0
        else:
             m2_SA.loc[i,"是否免除扣罚"] = 0
    else:
        if m2_SA.loc[i,"首次M2逾期率"] < 4.0:
            m2_SA.loc[i,'是否免除扣罚'] = 1
        else:
            m2_SA.loc[i,"是否免除扣罚"] = 0


m2_SA = m2_SA[["SA工号","是否免除扣罚"]]
m2_SA

          SA工号  是否免除扣罚
0     25100191       1
1      1050003       1
2     25170088       0
3     23250423       0
4     26120302       0
5     25060054       0
6     12100477       1
7     23140018       1
8     25200068       1
9     24240093       0
10    12130195       0
11    12250541       1
12     7260033       1
13    24110019       1
14     8140013       1
15    12060110       1
16     1120017       0
17    12120165       0
18     2190020       0
19    26240080       0
20    12240128       0
21    23170127       1
22    12070101       1
23     3200038       1
24    13080044       0
25    26120265       0
26     3080096       0
27     8260096       0
28     8120099       0
29     1140001       0
...        ...     ...
3001   8120126       0
3002  12060084       1
3003  26260170       1
3004   3120160       0
3005  12240507       1
3006  12100531       1
3007  12240443       0
3008  23230050       1
3009  25260114       0
3010  23170121       1
3011  12180034       0
3012  19190033       1
3013  25240200       0
3014  16120026       0
3015  12100175       1
3016  26250296       1
3017  12250733       0
3018   3100196       0
3019   4100097       0
3020  12230220       0
3021  12250723       1
3022   8040029       1
3023  12080333       0
3024  12060100       0
3025  26080258       0
3026  23230119       0
3027  10070008       1
3028   7060028       1
3029  13140016       0
3030  12200121       0

[3031 rows x 2 columns]

In [27]:
m2_plus = pd.merge(m2_plus,m2_SA,on="SA工号",how="left")


m2_plus['SA最终扣罚'] = 0
for i in range(len(m2_plus)):
    if m2_plus.loc[i,'是否免除扣罚'] == 1:
        m2_plus.loc[i,'SA最终扣罚'] = 0
    elif m2_plus.loc[i,'是否免除扣罚'] == 0:
        m2_plus.loc[i,'SA最终扣罚'] = m2_plus.loc[i,'最终扣罚']
    else:
        print("免除扣罚出现问题，请核实！")

In [28]:
m2_plus.to_csv("数据输出/SA的M2+单笔扣罚.csv")